name: Unit Test

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main, develop, pending-debug-ci, 1mgas-txpool-v0.3.0-pending-debug-ci]

jobs:
  unit_test:
    name: unit_test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - run: make test
